### ISSUE TITLE
Support for postgres custom schemas

### ISSUE THREAD

**Issue by tonyalaribe** [tchoutri/pg-entity#26]
Pg-entity seems to generate queries with the table name in quotes, which makes including schemas not work. 

```haskell
[INSERT] INSERT INTO "apis.requests_dump" ("created_at", "updated_at", "id") VALUES (null, null, null)


apitoolkit-server-test: SqlError {sqlState = "42P01", sqlExecStatus = FatalError, sqlErrorMsg = "relation \"apis.requests_dump\" does not exist", sqlErrorDetail = "", sqlErrorHint = ""}

```
In this example, the schema is apis, and the table name is requests_dump, defined like this:

```
instance Entity RequestDump where
  tableName = "apis.requests_dump"
  primaryKey = [field| id |]
  fields =
    [ [field| created_at |],
      [field| updated_at |],
      [field| id |],
      ...
    ]

```

**Comment by tchoutri** [comment]
@tonyalaribe That is interesting. I could see a "default" class method that falls back to `public` (or simply nothing), that you could overwrite with your schema. Then you don't have to put it in the `tableName`. So really something like:

```haskell
instance Entity RequestDump where
  tableName = "requests_dump"
  schema = "apis"
  primaryKey = [field| id |]
  fields =
    [ [field| created_at |],
      [field| updated_at |],
      [field| id |],
      ...
    ]
```

And the queries would be:

```SQL
INSERT INTO apis."requests_dump" ("created_at", "updated_at", "id")
  VALUES (null, null, null)
```

**Comment by tonyalaribe** [comment]
Yeah, this definitely solves the problem. Thanks!!

Btw, could this schema also be configured in the GenericEntity deriving mechanism?

**Comment by tchoutri** [comment]
Yup'

**Comment by tonyalaribe** [comment]
Awesome, thanks. 

Btw, i'm relatively new to haskell, but in other languages it's possible to make the SQL library skip certain fields when building the query from the struct. Eg in Go, you can add a tag `omitempty`, so that if that field is empty (zero value for that type), the field would be skipped in the query. How would you replicate such a pattern in haskell or with pg-entity?

For example, I have created_at and updated_at fields which are configured as NOT NULL but with defaults in postgres. And most times I don't want to set them myself, but I want to be able to query them. I made them maybe types in haskell, but then null just gets inserted into the query. 

```haskell
 INSERT INTO "requests_dump" ("created_at", "updated_at", "id", ...) VALUES (null, null, null, ...)
apitoolkit-server-test: SqlError {sqlState = "23502", sqlExecStatus = FatalError, sqlErrorMsg = "null value in column \"created_at\" of relation \"requests_dump\" violates not-null constraint", sqlErrorDetail = "Failing row contains (null, null, null, null,...).", sqlErrorHint = ""}

```

**Comment by tchoutri** [comment]
@tonyalaribe I gave some thought about it and it seems like you're trying to replicate what FromJSON and ToJSON offer.   

However, in `pg-entity`, there is only one typeclass ("contract" with the outside world) for serialisation and de-serialisation, which means that if you choose to ignore some fields on insert, you'll have to ignore them on select as well. This doesn't seem to be what you want.

My advice is to create those values on the Haskell side. It's fairly inexpensive to do so, and it will save you from trying to wrangle Maybes and DEFAULT values. :)

**Comment by tchoutri** [comment]
That being said you could also do insertion / querying DAOs, which will make you create two different records with two different sets of fields, pointing at the same table. Not ideal but when you don't control the schema it's perfect.

**Comment by tonyalaribe** [comment]
I see, separate insertion and querying DAOs is what I imagined to the only approach in haskell. 

Btw, can you explain  this more:  `My advice is to create those values on the Haskell side. It's fairly inexpensive to do so, and it will save you from trying to wrangle Maybes and DEFAULT values` ?  Or did you also mean using DAOs?

**Comment by tonyalaribe** [comment]
Ah, you meant to set the fields in the records on the Haskell side instead or try to skip them somehow. I think I'll do this where possible. Otherwise, I can fall back to DAOs. Thanks!!

**Comment by tchoutri** [comment]
> Btw, can you explain this more: 

Well, let's consider you have such a struct:

```haskell

data Record = Record
  { recId :: UUID
  , recVal :: Text
  , createdAt :: UTCTime
  , updatedAt :: UTCTime
  }
  deriving Entity
    via (GenericEntity '[TableName "records"] Record)

mkRecord :: Text -> IO Record
mkRecord recVal = do
  recId <- UUID.nextRandom
  timestamp <- Time.getCurrentTime
  pure $ Record{recId, recVal, createdAt = timestamp, updatedAt = timestamp}

insertRecord :: Record -> DBT IO ()
insertRecord = insert @Record
```

**Comment by tonyalaribe** [comment]
Yeah, I see. That makes sense. Thanks a lot, this makes things clearer for me as well! 🙏

**Comment by tchoutri** [comment]
You're welcome! :)
