### ISSUE TITLE
Issues with Null handling and query argument order.

### ISSUE THREAD

**Issue by tonyalaribe** [tchoutri/pg-entity#38]
I have a query such this:
```haskell 

selectOngoingAnomaliesForEndpoint :: Projects.ProjectId -> Endpoints.EndpointId -> DBT IO (Vector AnomalyVM)
selectOngoingAnomaliesForEndpoint pid eid = query Select q opt
  where
    q = _selectWhere @AnomalyVM [[field| project_id |], [field| endpoint_id |], [field| acknowleged_at |], [field| archived_at |]]
    opt = (pid, eid, Null, Null)
```

But I noticed 2 issues with the generated query. 
1.  When checking for null with Postgres, we're expected to use `is` instead of `=`. 
2. It seems the options are applied in a different order from the fields list given the _selectWhere

Generated sql:
```
SELECT anomalies_vm."id",... FROM apis."anomalies_vm" WHERE "project_id" = 'project id val' AND "acknowleged_at" = 'endpoint_id val' AND "archived_at" = null AND "endpoint_id" = null
```

EDIT:
It seems the order is based on the field positions in the underlying struct. Is this intended behaviour?

**Comment by tchoutri** [comment]
@tonyalaribe Yes, due to how the query generation is done, it's going to be more complex to produce a `Null`-aware select combinator, because you'd have to signal to `_where` that some of your place-holders are going to be `NULL`. 

You're going to have to roll that one by hand at the moment. 

> It seems the order is based on the field positions in the underlying struct. Is this intended behaviour?

Yes, but this ought to be documented. :)

**Comment by tonyalaribe** [comment]
Thanks @tchoutri , I’ll work around it :)

**Comment by tchoutri** [comment]
@tonyalaribe Thanks again for all the tickets you open, this is invaluable to me. :)

**Comment by tonyalaribe** [comment]
I'm a very happy user of pg-entity. I really appreciate the work you put into this. And also the indirect haskell mentorship I get through the conversations in these issues. Thanks as well !!
